version: "3.8"

services:
  # ------------------------------------------------------------------
  # 生产者 1 — 爬取"任务1"的微博
  # ------------------------------------------------------------------
  producer-1:
    build: .
    container_name: pi-producer-1
    command: python producer.py spider_demo.yaml 0
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=1234
    restart: unless-stopped
    volumes:
      - ./download:/app/download
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ------------------------------------------------------------------
  # 生产者 2 — 爬取"任务2"的微博
  # ------------------------------------------------------------------
  producer-2:
    build: .
    container_name: pi-producer-2
    command: python producer.py spider_demo.yaml 1
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=1234
    restart: unless-stopped
    volumes:
      - ./download:/app/download
    extra_hosts:
      - "host.docker.internal:host-gateway"
