# config/spiders.yaml
sites:
 - name: "weibo"
   enabled: true
   spider_class: "core.weibo.WeiBoSpider"
   redis_key_prefix: "weibo"
   flag: true
   url: "https://weibo.com/u/7893929649?tabtype=feed"
   users:
    - "user_001"

 - name: "bilibili"
   enabled: false
   spider_class: "core.bilibili.BiliBiliSpider"
   redis_key_prefix: "bilibili"
   users:
    - "user_001"


